language:
  python

dist:
  xenial

script:
  make build

before_deploy:
  make tidy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: terse.ashenm.ml

notifications:
  slack:
    secure: O58kqOIBWrzYptvI4bJSISHVgfysT08OJ63aqxLbVsh8Cw79Zla0d940JMjc3IbLsqkdlEW2VH9tb7lCLXZ08XXEpdx9QmRzP1EkEBQ3xQmnW3PDNxi1bPcC1twORLFd2HWkkGnZMLU0rZ42m37uf0PDQTJAUTQajON5t8LT5qlYovPvZZpuFoRtEEQCW+l/mcXTYNX7CtYgB2z4HZnNPmKFNYIYdEezXTD5uoCkgz11Jvb6Pvt6fMJYxQz8E/b7wV0/vQl5/rPBFc+kVRahZ9Hr7JTC4JqoALS/hPk75lR7MAXH3bppXx93zqpegaAgWCzMqzj768KXTjV9tIEJ23XA3CDn1vUko6N1WPUBncweMlZqsBWl7yl+Pe/rOMkkx6BLEIE4F31b09CVT/2IPiETa26bLpXvTWmhlpPvkCag+ydKpMS1ywjbnI/Ap3xFhSGiY6afslVH0GKItVLwtOkfjv9dRF7Tard7dWqs8jdwkZp1ULI22+t9MRwY6PyOpoM2UhzVKU3+ozh2OL+1i522FNhLPmq/3OSmFcU8B1B23SiVkm3iWIblzo+JZkSE7BZbFwJLn6nEE0VSgBLEnComl9k0CvNFGJfuqWSJCPFABsQKQCdZDNPcfGSxxGoCj80v3qdQg/5jI/qJpmWRRRPVkJ+AvaGFjsIIZGPg0Lo=

# vim: set expandtab shiftwidth=2 syntax=yaml:
