- path: example
  url: https://www.example.com/
- path: html5-logo
  url: https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/800px-HTML5_logo_and_wordmark.svg.png

# vim: set expandtab shiftwidth=2 syntax=yaml:
