#!/usr/bin/env python3
#
# Build Project
# https://github.com/ashenm/jekyll-terse
#
# Ashen Gunaratne
# mail@ashenm.ml
#

from os import P_WAIT, spawnlp
from yaml import FullLoader, load

# grab routes
with open('_data/routes.yml', 'rb') as stream:
  routes = load(stream=stream, Loader=FullLoader)

# build pages for routes
for route in routes:
  with open ('{}.html'.format(route['path']), 'tw') as file:
    file.writelines([
      '---\n',
      'title: {}\n'.format(route['path'].capitalize()),
      'permalink: {}\n'.format(route.get('permalink')) if route.get('permalink') else '',
      'redirect_to: {}\n'.format(route['url']),
      '---\n'
    ])

# build site
spawnlp(P_WAIT, 'jekyll', 'jekyll', 'build', '--safe', '--profile')

# vim: set expandtab shiftwidth=2 syntax=python:
