#!/usr/bin/env python3
#
# List Shortened Routes
# https://github.com/ashenm/jekyll-terse
#
# Ashen Gunaratne
# mail@ashenm.ml
#

from yaml import FullLoader, load

with open('_data/routes.yml', 'rb') as stream:
  routes = load(stream=stream, Loader=FullLoader)

for route in routes:
  print(f'''\033[91m/{route['path'].lower()}\033[0m -> \033[96m{route['url'].lower()}\033[0m''')

# vim: set expandtab shiftwidth=2 syntax=python:
